name: image-denoising
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pytorch==2.1.2
  - torchvision==0.16.2 
  - torchaudio==2.1.2
  - pytorch-cuda=12.1
  - lightning
  - transformers
  - numpy
  - pandas
  - Pillow
  - scikit-learn
  - pip
  - pip:
    - opencv-python
    - image-similarity-measures[speedups]
    - ipykernel
    - tqdm
    - einops
    - pyyaml
